apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-reddi
  namespace: rediit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reddit
  template:
    metadata:
      labels:
        app: reddit
    spec:
      containers:
      - name: reddit-app
        image: vinayjadhav/Reddit-clone-app:replaceImageTag
        ports:
          - containerPort: 3000
        resources:
          limits:
            cpu: 1m
            memory: 512Mi
          requests:
            cpu: 0.5m
            memory: 256Mi


        