apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-maven
  namespace: java-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java
      version: v1.0.0
  template:
    metadata:
      labels:
        app: java
    spec:
      containers:
      - name: app
        image: vinayjadhav/app-Java:latest
        ports:
          - containerPort: 8080
        


---
apiVersion: v1
kind: Service
metadata:
  name: svc-app
  namespace: java-app
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: java
  type: NodePort